name: ASP.NET Core CI/CD Pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '8.x'
  ASPNETCORE_ENVIRONMENT: 'Production'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~\.nuget\packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: bin/Release/net8.0

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: dotnet test ./OnlineStore.Catalog.Tests/OnlineStore.Catalog.Tests.csproj --no-build --verbosity normal

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: bin/Release/net8.0

  publish:
    needs: [build, test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Upload publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-output
          path: bin/Release/net8.0